### ISSUE TITLE
Official lib

### ISSUE THREAD

**Issue by natcl** [vizkits/node-red-nodes#1]
There is already an official bean library made by the folks at PunchThrough, does this one add functionality ?

See: https://github.com/PunchThrough/node-red-contrib-bean

**Comment by vizkits** [comment]
Hi, this one does not add functionality compared to the official library. It's just a convenient node that combines acc, temp in one single node.

**Comment by natcl** [comment]
Got it Thanks !

**Comment by vizkits** [comment]
Also this uses a different node module (bean-io) which in turn uses the same ble-bean used by the official bean.
